# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'PinmarkApp' do
	pod 'ObjectiveSugar', '~> 1.1.0'
end

target 'PinmarkAppTests' do
  #pod 'Kiwi', '~> 2.3'
  pod 'Kiwi',:git =>'https://github.com/kiwi-bdd/Kiwi.git' 
end

